apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: linkerd-helm-release
spec:
  releaseName: linkerd
  chart:
    spec:
      chart: linkerd2
      version: 2.9.3
      sourceRef:
        kind: HelmRepository
        name: linkerd-helm-repo
  interval: 0h15m0s
  targetNamespace: linkerd
  install:
    remediation:
      retries: 3
  upgrade:
    remediation:
      retries: 3
  valuesFrom:
    - kind: ConfigMap
      name: linkerd-values-from
      optional: true
